# Generated by Django 5.2.4 on 2025-07-17 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='transactions',
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.wallet'),
            preserve_default=False,
        ),
    ]
