# Generated by Django 5.2.4 on 2025-07-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_category_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('name', 'currency'), name='unique_wallet_name_currency'),
        ),
    ]
