# Generated by Django 5.2.4 on 2025-07-29 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_category_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallet',
            name='unique_wallet_name_currency',
        ),
    ]
