# Generated by Django 5.2.4 on 2025-07-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_wallet_unique_wallet_name_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_income',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
